apiVersion: apps/v1
kind: Deployment
metadata:
  name: iweblensedeploy
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: mehtapreeti09/iweblense:latest
        ports:
        - containerPort: 2020
---
apiVersion: v1
kind: Service
metadata:
  name: iweblenseservice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
    - targetPort: 2020
      nodePort: 30200
      port: 80
